import { ISpellsBeastsSelectors } from '../game-types/interfaces';

export const spellsSelectors: ISpellsBeastsSelectors = {
  fire: 'fire',
  огонь: 'fire',
  water: 'water',
  вода: 'water',
  wind: 'wind',
  ветер: 'wind',
  light: 'light',
  свет: 'light',
  thunder: 'thunder',
  гром: 'thunder',
  'heavy flame': 'heavy-flame',
  'сильное пламя': 'heavy-flame',
  maelstrom: 'maelstrom',
  водоворот: 'maelstrom',
  'whirl gale': 'whirl-gale',
  'завихрение ветра': 'whirl-gale',
  soundwave: 'soundwave',
  'громовая волна': 'soundwave',
  'fiery hail': 'fiery-hail',
  'огненный град': 'fiery-hail',
  'radiant wall': 'radiant-wall',
  'стена света': 'radiant-wall',
  'blusting blow': 'blusting-blow',
  'удар грома': 'blusting-blow',
  'rising glow': 'rising-glow',
  'восход сияния': 'rising-glow',
  cloudburst: 'cloudburst',
  'водяная буря': 'cloudburst',
  'shining vortex': 'shining-vortex',
  'сияющий вихрь': 'shining-vortex',
  'furious flow': 'furious-flow',
  'яростный поток': 'furious-flow',
  flurryspout: 'flurryspout',
  'воздушный смерч': 'flurryspout',
  aquaswirl: 'aquaswirl',
  'водяной смерч': 'aquaswirl',
  'massive tornado': 'massive-tornado',
  'гигантский торнадо': 'massive-tornado',
  'electrical discharge': 'electrical-discharge',
  'удар молнии': 'electrical-discharge',
  'volcanic hurricane': 'volcanic-hurricane',
  'пламенный ураган': 'volcanic-hurricane',
  'ferocious twister': 'ferocious-twister',
  'яростный шквал': 'ferocious-twister',
  'luminous pillar': 'luminous-pillar',
  'световой столп': 'luminous-pillar',
  'vortical typhoon': 'vortical-typhoon',
  'вихревой тайфун': 'vortical-typhoon',
  'burning onslaught': 'burning-onslaught',
  'огненный натиск': 'burning-onslaught',
  'elemental chars': 'elemental-chars',
  'стихийные чары': 'elemental-chars',
  'elemental high magic': 'elemental-high-magic',
  'высшая стихийная магия': 'elemental-high-magic',
  'elemental great enchantment': 'elemental-great-enchantment',
  'великое стихийное волшебство': 'elemental-great-enchantment',
};

export const beastsSelectors: ISpellsBeastsSelectors = {
  'cave beast': 'cave-beast',
  'пещерное чудище': 'cave-beast',
  'swamp beast': 'swamp-beast',
  'болотное чудище': 'swamp-beast',
  'sand beast': 'sand-beast',
  'песчанное чудище': 'sand-beast',
  'stone beast': 'stone-beast',
  'каменное чудище': 'stone-beast',
  'forest beast': 'forest-beast',
  'лесное чудище': 'forest-beast',
  'cloud monster': 'cloud-monster',
  'облачный монстр': 'cloud-monster',
  'waterfall monster': 'waterfall-monster',
  'водопадный монстр': 'waterfall-monster',
  'lava monster': 'lava-monster',
  'лавовый монстр': 'lava-monster',
  'tornado monster': 'tornado-monster',
  'ураганный монстр': 'tornado-monster',
};
