import { ISpellsBeastsSelectors } from '../game-types/interfaces';

export const spellsSelectors: ISpellsBeastsSelectors = {
  fire: 'fire',
  огонь: 'fire',
  water: 'water',
  вода: 'water',
  wind: 'wind',
  ветер: 'wind',
  light: 'light',
  свет: 'light',
  thunder: 'thunder',
  гром: 'thunder',
  'heavy flame': 'heavy-flame',
  'сильное пламя': 'heavy-flame',
  maelstrom: 'maelstrom',
  водоворот: 'maelstrom',
  'wind whirl': 'wind-whirl',
  'завихрение ветра': 'wind-whirl',
  soundwave: 'soundwave',
  'громовая волна': 'soundwave',
  'fiery hail': 'fiery-hail',
  'огненный град': 'fiery-hail',
  'ligth wall': 'ligth-wall',
  'стена света': 'ligth-wall',
  'thunder blow': 'thunder-blow',
  'удар грома': 'thunder-blow',
  'rising glow': 'rising-glow',
  'восход сияния': 'rising-glow',
  'water storm': 'water-storm',
  'водяная буря': 'water-storm',
  'shining vortex': 'shining-vortex',
  'сияющий вихрь': 'shining-vortex',
  'furious flow': 'furious-flow',
  'яростный поток': 'furious-flow',
  windspout: 'windspout',
  'воздушный смерч': 'windspout',
  waterspout: 'waterspout',
  'водяной смерч': 'waterspout',
  'massive tornado': 'massive-tornado',
  'гигантский торнадо': 'massive-tornado',
  'lightning blast': 'lightning-blast',
  'удар молнии': 'lightning-blast',
  'fiery hurricane': 'fiery-hurricane',
  'огненный ураган': 'fiery-hurricane',
  'furious whirlwind': 'furious-whirlwind',
  'яростный ветер': 'furious-whirlwind',
  'luminous pillar': 'luminous-pillar',
  'световой столп': 'luminous-pillar',
  'whirlwind lightning': 'whirlwind-lightning',
  'вихревая молния': 'whirlwind-lightning',
  'burning onslaught': 'burning-onslaught',
  'огненный натиск': 'burning-onslaught',
  'elemental chars': 'elemental-chars',
  'стихийные чары': 'elemental-chars',
  'elemental high magic': 'elemental-high-magic',
  'высшая стихийная магия': 'elemental-high-magic',
  'elemental great enchantment': 'elemental-great-enchantment',
  'великое стихийное волшебство': 'elemental-great-enchantment',
};

export const beastsSelectors: ISpellsBeastsSelectors = {
  'cave beast': 'cave-beast',
  'пещерное чудище': 'cave-beast',
  'swamp beast': 'swamp-beast',
  'болотное чудище': 'swamp-beast',
  'sand beast': 'sand-beast',
  'песчанное чудище': 'sand-beast',
  'stone beast': 'stone-beast',
  'каменное чудище': 'stone-beast',
  'forest beast': 'forest-beast',
  'лесное чудище': 'forest-beast',
  'cloud monster': 'cloud-monster',
  'облачный монстр': 'cloud-monster',
  'waterfall monster': 'waterfall-monster',
  'водопадный монстр': 'waterfall-monster',
  'lava monster': 'lava-monster',
  'лавовый монстр': 'lava-monster',
  'tornado monster': 'tornado-monster',
  'ураганный монстр': 'tornado-monster',
};
