export const enKeys = [
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
];

export const ruKeys = [
  'Й',
  'Ц',
  'У',
  'К',
  'Е',
  'Н',
  'Г',
  'Ш',
  'Щ',
  'З',
  'Х',
  'Ъ',
  'Ф',
  'Ы',
  'В',
  'А',
  'П',
  'Р',
  'О',
  'Л',
  'Д',
  'Ж',
  'Э',
  'Я',
  'Ч',
  'С',
  'М',
  'И',
  'Т',
  'Ь',
  'Б',
  'Ю',
];

export const enLibrary = {
  startModalTitle: 'Welcome to the Typing Hero!',
  startModalParagOne: 'Your task is to catch all the letters that appear on the playing field',
  startModalParagTwo:
    'Points are awarded for each letter caught. Throughout the level, you will also be shown your accuracy. If you have passed the level to the end - it is considered passed and falls into your thrift-box!',
  startModalParagThree: 'Catch letters, score points, practice accuracy!',
  startModalButton: "let's start!",

  baseLvlContent: 'get your first points',
  appButton: 'back to games',
  sandboxButton: 'sandbox',

  sandboxModalText:
    'In the sandbox, you can choose the speed of the letters, the number of columns and the duration of the level. Sandbox points count towards the overall score, but, like levels, are overwritten with each replay.',
  sandboxInputSpeed: 'speed (in seconds): 1 to 10',
  sandboxInputDuration: 'duration (in seconds): 10 to 150',
  sandboxInputColumns: 'columns: 3 to 7',
  sandboxButtonStart: 'start',
  sandboxCloseModal: 'close',

  level: 'level',
  levelButton: 'back to menu',
  leveCompleted: 'level completed!',

  score: 'score',
  accuracy: 'accuracy',
  currentScore: 'current',
  currentAccuracy: 'current',
  prevousBestScore: 'Prevous best',
  prevousBestAccuracy: 'Prevous best',
  bestScore: 'best',
  bestAccuracy: 'best',
  total: 'total',
  totalScore: 'score',
  average: 'average',

  achievementTitle: 'New achievement',
};

export const ruLibrary = {
  startModalTitle: 'Добро пожаловать в игру Typing Hero!',
  startModalParagOne: 'Ваша задача — успеть поймать все буквы, появляющиеся на игровом поле.',
  startModalParagTwo:
    'За каждую пойманную букву начисляются очки. На протяжении уровня вам будет также выводиться ваша точность. Если вы прошли уровень до конца - он считается пройденным и падает вам в копилку!',
  startModalParagThree: 'Ловите буквы, набирайте очки, практикуйтесь в точности!',
  startModalButton: 'вперёд!',

  baseLvlContent: 'получите первые очки',
  appButton: 'вернуться к играм',
  sandboxButton: 'песочница',

  sandboxModalText:
    'В песочнице вы можете сами выбрать скорость букв, количество колонок и продолжительность уровня. Очки песочницы идут в общий зачёт, но, как и у уровней, перезаписываются при каждом повторном перепрохождении.',
  sandboxInputSpeed: 'скорость (в секундах): от 1 до 10',
  sandboxInputDuration: 'продожительность (в секундах): от 10 до 150',
  sandboxInputColumns: 'колонки: от 3 to 7',
  sandboxButtonStart: 'начать',
  sandboxCloseModal: 'закрыть',

  level: 'уровень',
  levelButton: 'вернуться в меню',
  leveCompleted: 'уровень пройден!',

  score: 'очки',
  accuracy: 'точность',
  currentScore: 'текущие',
  currentAccuracy: 'текущая',
  prevousBestScore: 'Предыдущие лучшие',
  prevousBestAccuracy: 'Предыдущая лучшая',
  bestScore: 'лучшие',
  bestAccuracy: 'лучшая',
  total: 'Всего',
  totalScore: 'очков',
  average: 'Средняя',

  achievementTitle: 'Новое достижение',
};
